name: Suggestion Form
description: Describe thy wishes (but no promises)
body:
  - type: textarea
    attributes:
      label: The Suggestion in Question
      description: Describe in detail what you'd want the mod to do which it already doesn't do
    validations:
      required: true
  - type: textarea
    attributes:
      label: The Law of Equivalent Exchange
      description: Describe what you would give up in order to have the suggestion become reality in non-monetary terms
      placeholder: "Ex: An eighth of my soul, the head of my largest Optimus Prime figurine"
    validations:
      required: true